title: limetyapple's blog
lang: zh-CN
description: none

# theme: jekyll-rtd-theme
remote_theme: rundocs/jekyll-rtd-theme

edit: true

copyright:
  revision: true

addons:
  - github
  - gems
  - analytics

addons_branch: true

# sort
readme_index:
  with_frontmatter: true

sass:
  style: compressed

exclude:
  - Makefile
  - Gemfile
  - Gemfile.lock
